### ISSUE TITLE
The librechat helm chart LibreChat v0.7.5-rc1 not supported the OpenAI O1 models

### ISSUE THREAD

**Issue by SharpLu** [bat-bs/helm-charts#30]
Hi @hofq ,

Hope you are doing well! Thank you for your contribution to open source software
I'm Librechat helm chart user, this is great tool can deploy to kubernates, i just found the current version  LibreChat v0.7.5-rc1 seems not working with openai o1 models and i confirmed with librechat they said the they did the update on LibreChat v0.7.5-rc2 and now they o1 models are enabled in the latest version, just wondering does librechat helm chart community have plan to do a release recently? 

Thank you so much !

**Comment by hofq** [comment]
Hi @SharpLu 

Currently, we do a release on every official librechat releaase. Since the Versions mentioned are Release Candidates you have to test it yourself and changge the tag in your values file.

For that you can just change the image-tag in your librechat values file or params:

```yaml
image:
  tag: "v0.7.5-rc2"
```

If anything breaks or everything works fine in the new RC please let me know

**Comment by hofq** [comment]
Feel free to reopen if you have any issues
